### ISSUE TITLE
Isbn::extract doesn't work with space separated ISBNs

### ISSUE THREAD

**Issue by konieczkow** [altmetric/identifiers#15]
I tried to use the library like so:
```php
Isbn::extract("9780854045877 9781847552518")
```
and got `[]` back.

If I use it on 
```php
Isbn::extract("9780854045877\n9781847552518")
```
though it gives me both ISBNs. 
Is there a reason why it doesn't extract anything in the first scenario?

**Comment by mudge** [comment]
The issue here is how we sanitise ISBNs prior to extraction by [removing dashes and whitespace between numbers](https://github.com/altmetric/php-identifiers/blob/fa3e9782e26ef73fde714d18520e3a11289682e8/src/Isbn.php#L25): this causes two valid ISBNs separated by a single space to be collapsed into a single invalid string of numbers.

If you use more than one space, the extraction works, e.g.

```php
$this->assertEquals(['9780805069099', '9780671879198'], Isbn::extract('9780805069099  9780671879198'));
```

This might be a tricky one...
